### ISSUE TITLE
Client index -1 is invalid

### ISSUE THREAD

**Issue by kiri3shka** [baferpro/JWP-MiniGames#5]
L 07/28/2020 - 19:50:15: [SM] Exception reported: Client index -1 is invalid
L 07/28/2020 - 19:50:15: [SM] Blaming: jwp_mg.smx
L 07/28/2020 - 19:50:15: [SM] Call stack trace:
L 07/28/2020 - 19:50:15: [SM]   [0] IsClientInGame
L 07/28/2020 - 19:50:15: [SM]   [1] Line 466, jwp/mg/events.sp::OnTakeDamage

**Comment by WhyFaust** [comment]
https://github.com/baferpro/JWP-MiniGames/commit/9af17827025f1824ccfb96f561330028ff10c212
